### ISSUE TITLE
Will Source code for paper be published

### ISSUE THREAD

**Issue by xinedison** [yaojieliu/ECCV2018-FaceDeSpoofing#2]
Hello, Dr Liu,
     Thanks for your work in Learning "Deep Models for Face Anti-Spoofing: Binary or Auxiliary Supervision". I am working in repeat your experiment in the paper with mxnet. But some detail in the code is not clear for me. Will the source code for the paper "Learning Deep Models for Face Anti-Spoofing: Binary or Auxiliary Supervision" be published in github soon?

**Comment by yaojieliu** [comment]
No, the source code of that paper is licensed.
