### ISSUE TITLE
Whether The train code work

### ISSUE THREAD

**Issue by xinedison** [yaojieliu/ECCV2018-FaceDeSpoofing#6]
Hello, Dr Liu
      Thank you for sharing code. I want to train model to repeat the experiment , But i found the train code is not work, Some variable like cifar10, cifar10_input is not defined in the code. Is thres something missing for my run.

**Comment by yaojieliu** [comment]
For the cifar10, cifar10_input, I've fixed the issue.

For other problems, please contact amin.jourabloo@gmail.com.
