### ISSUE TITLE
NameError: name 'cifar10_input' is not defined

### ISSUE THREAD

**Issue by cvJie** [yaojieliu/ECCV2018-FaceDeSpoofing#7]
hi，yaojie:
      I want to run Train.py, and erroe is  :

"Architecture.py", line 31, in <module>
         IMAGE_SIZE = cifar10_input.IMAGE_SIZE
NameError: name 'cifar10_input' is not defined

please give me some advices.thanks

**Comment by yaojieliu** [comment]
Fixed, it should be data_train. Thank you.
